### ISSUE TITLE
Example working with EF Core

### ISSUE THREAD

**Issue by jbliss1234** [mkmarek/graphql-dotnetcore#67]
Could you please provide an example of using graphql-dotnetcore working with EF Core, for a query and mutation

**Comment by mkmarek** [comment]
Hi, sure I can create an example during the upcoming weekend.  I'll post a link here afterwards.

**Comment by bancroftway** [comment]
+1 for this. Looking forward to the sample.

**Comment by mkmarek** [comment]
Created a repo at https://github.com/mkmarek/graphql-dotnetcore-ef-example for now it contains just one query and one mutation but it should still explain one of the possibilities how to use it. I'll add more stuff  and some furter explanation during the weekend hopefully. It went to be a little bit more difficult than I initially expected. But it's quite simmilar to a way how we use this library for real projects.

But basically it uses the CQRS pattern which I think works with GraphQL really well. For DB I used MSSQL but you can surely change that to whatever suits you. For the database layer I picked unit of work pattern using https://github.com/arch/UnitOfWork library.

It also uses the ASP.NET core DI container quite heavily. You can notice that the graphql schema class doesn't really have anything. The flow is inverse. The types themselves are registering into the schema. The reason for that is [here](https://github.com/mkmarek/graphql-dotnetcore-ef-example/blob/master/src/graphql-dotnetcore-ef-example/GraphQL/ObjectTypes/PagedListSchemaType.cs#L9) Another workaround would be of course possible if It managed those schema types outside the DI container.

I'm running quite old version of .NET core on my current laptop so you might have to upgrade the project.

To run it you need to:

- change the connection string at appsettings.json
- run the `dotnet ef database update` to populate your database
- run it with `dotnet run` or through visual studio

Then if you go to http://localhost:<yourport>/public/index.html you should see the GraphiQL interface and there you can play around. 

Enjoy!
Marek
